export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELETCED_PRODUCT: 'SELETCED_PRODUCT',
    REMOVE_SELETCED_PRODUCT: 'REMOVE_SELETCED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    PLACE_ORDER: 'PLACE_ORDER'
}